machines:
  - name: qcs6490-rb3gen2-vision-kit
    description: "qcs6490 rb3gen2 vision kit"
    parameters: null
  - name: qcs9075-rb8-core-kit
    description: "qcs9075 rb8 core kit"
    parameters: null
  - name: qcs8300-ride-sx
    description: "qcs8300 ride sx"
    parameters: null